### ISSUE TITLE
Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by findel** [ShyykoSerhiy/skyweb#20]
I've received two new errors from the skyweb library today. I wonder if something has changed in Skype for Web?

```
TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (C:\SpypeLive\node_modules\skyweb\dist\message_service.js:25:50)
    at self.callback (C:\SpypeLive\node_modules\skyweb\node_modules\request\request.js:198:22)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at Request.onRequestError (C:\SpypeLive\node_modules\skyweb\node_modules\request\request.js:877:8)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at TLSSocket.socketErrorListener (_http_client.js:262:9)
    at emitOne (events.js:90:13)
    at TLSSocket.emit (events.js:182:7)


TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (C:\SpypeLive\node_modules\skyweb\dist\polling\poll.js:22:54)
    at self.callback (C:\SpypeLive\node_modules\skyweb\node_modules\request\request.js:198:22)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at Request.onRequestError (C:\SpypeLive\node_modules\skyweb\node_modules\request\request.js:877:8)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at TLSSocket.socketErrorListener (_http_client.js:262:9)
    at emitOne (events.js:90:13)
    at TLSSocket.emit (events.js:182:7)
```

Sorry for bombarding you with new issues. Hope you don't mind.

**Comment by ShyykoSerhiy** [comment]
Thx, for the issue.

**Comment by findel** [comment]
This appears to be fixed. But now I have a question which I've opened as #24 .
