### ISSUE TITLE
Demo instructions in README are outdated

### ISSUE THREAD

**Issue by erikcw** [ShyykoSerhiy/skyweb#39]
A couple of problems with the demo.

1)  The path to the demo from the README is no longer correct.  The README instructs new users to `cd dist/demo`, but the demo directory has been moved to `dist/src/demo/demo.js`.

2) When running `node demo.js user pw` after changing to the above mentioned directory, the following traceback is dumped.

``` js
/Users/erik/git/skyweb/dist/src/demo/demo.js:8
var skyweb = new skyweb_1.default();
             ^

TypeError: skyweb_1.default is not a constructor
    at Object.<anonymous> (/Users/erik/git/skyweb/dist/src/demo/demo.js:8:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3
```

**Comment by scumdog** [comment]
Comment out 
../skyweb.js line 53 ie "//exports = Skyweb;"

--- a/dist/src/skyweb.js
+++ b/dist/src/skyweb.js
@@ -50,8 +50,8 @@ var Skyweb = (function () {
     };
     return Skyweb;
 }());
-exports = Skyweb;
+//exports = Skyweb;
 exports.Skyweb = Skyweb;
 Object.defineProperty(exports, "__esModule", { value: true });
 exports.default = Skyweb;
