### ISSUE TITLE
TypeError: currentValue.bind is not a function

### ISSUE THREAD

**Issue by phillipadsmith** [ShyykoSerhiy/skyweb#73]
Any ideas on this? 

```
➜  demo git:(master) ✗ node demo.js un pw
TypeError: currentValue.bind is not a function
   at /Users/username/Development/skyweb/dist/src/login.js:26:63
    at tryCatch (/Users/username/Development/skyweb/node_modules/es6-promise/dist/es6-promise.js:410:12)
    at invokeCallback (/Users/username/Development/skyweb/node_modules/es6-promise/dist/es6-promise.js:425:13)
    at /Users/username/Development/skyweb/node_modules/es6-promise/dist/es6-promise.js:172:16
    at flush (/Users/username/Development/skyweb/node_modules/es6-promise/dist/es6-promise.js:121:5)
    at process._tickCallback (internal/process/next_tick.js:150:11)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
```

**Comment by ShyykoSerhiy** [comment]
Well, that's just embarrassing... 
Fixed in 0.4.3
